//go:build !ignore_autogenerated

/*
Copyright (c) 2026.

MIT License - see LICENSE file for details.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicy) DeepCopyInto(out *RetentionPolicy) {
	*out = *in
	if in.MaxSuspendedWorkspaces != nil {
		in, out := &in.MaxSuspendedWorkspaces, &out.MaxSuspendedWorkspaces
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicy.
func (in *RetentionPolicy) DeepCopy() *RetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateProviderConfig) DeepCopyInto(out *SubstrateProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateProviderConfig.
func (in *SubstrateProviderConfig) DeepCopy() *SubstrateProviderConfig {
	if in == nil {
		return nil
	}
	out := new(SubstrateProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubstrateProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateProviderConfigList) DeepCopyInto(out *SubstrateProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubstrateProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateProviderConfigList.
func (in *SubstrateProviderConfigList) DeepCopy() *SubstrateProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(SubstrateProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubstrateProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateProviderConfigSpec) DeepCopyInto(out *SubstrateProviderConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateProviderConfigSpec.
func (in *SubstrateProviderConfigSpec) DeepCopy() *SubstrateProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SubstrateProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateSuspendPolicy) DeepCopyInto(out *SubstrateSuspendPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateSuspendPolicy.
func (in *SubstrateSuspendPolicy) DeepCopy() *SubstrateSuspendPolicy {
	if in == nil {
		return nil
	}
	out := new(SubstrateSuspendPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateTemplateReference) DeepCopyInto(out *SubstrateTemplateReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateTemplateReference.
func (in *SubstrateTemplateReference) DeepCopy() *SubstrateTemplateReference {
	if in == nil {
		return nil
	}
	out := new(SubstrateTemplateReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateWorkspaceProfile) DeepCopyInto(out *SubstrateWorkspaceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateWorkspaceProfile.
func (in *SubstrateWorkspaceProfile) DeepCopy() *SubstrateWorkspaceProfile {
	if in == nil {
		return nil
	}
	out := new(SubstrateWorkspaceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubstrateWorkspaceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateWorkspaceProfileList) DeepCopyInto(out *SubstrateWorkspaceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubstrateWorkspaceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateWorkspaceProfileList.
func (in *SubstrateWorkspaceProfileList) DeepCopy() *SubstrateWorkspaceProfileList {
	if in == nil {
		return nil
	}
	out := new(SubstrateWorkspaceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubstrateWorkspaceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateWorkspaceProfileSpec) DeepCopyInto(out *SubstrateWorkspaceProfileSpec) {
	*out = *in
	out.TemplateRef = in.TemplateRef
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(SubstrateSuspendPolicy)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(RetentionPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateWorkspaceProfileSpec.
func (in *SubstrateWorkspaceProfileSpec) DeepCopy() *SubstrateWorkspaceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(SubstrateWorkspaceProfileSpec)
	in.DeepCopyInto(out)
	return out
}
