//go:build !ignore_autogenerated

/*
Copyright (c) 2026.

MIT License - see LICENSE file for details.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicy) DeepCopyInto(out *RetentionPolicy) {
	*out = *in
	if in.MaxSuspendedWorkspaces != nil {
		in, out := &in.MaxSuspendedWorkspaces, &out.MaxSuspendedWorkspaces
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicy.
func (in *RetentionPolicy) DeepCopy() *RetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxDurableVolume) DeepCopyInto(out *SandboxDurableVolume) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxDurableVolume.
func (in *SandboxDurableVolume) DeepCopy() *SandboxDurableVolume {
	if in == nil {
		return nil
	}
	out := new(SandboxDurableVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxProviderConfig) DeepCopyInto(out *SandboxProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxProviderConfig.
func (in *SandboxProviderConfig) DeepCopy() *SandboxProviderConfig {
	if in == nil {
		return nil
	}
	out := new(SandboxProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxProviderConfigList) DeepCopyInto(out *SandboxProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxProviderConfigList.
func (in *SandboxProviderConfigList) DeepCopy() *SandboxProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(SandboxProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxProviderConfigSpec) DeepCopyInto(out *SandboxProviderConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxProviderConfigSpec.
func (in *SandboxProviderConfigSpec) DeepCopy() *SandboxProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSuspendPolicy) DeepCopyInto(out *SandboxSuspendPolicy) {
	*out = *in
	in.Volume.DeepCopyInto(&out.Volume)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSuspendPolicy.
func (in *SandboxSuspendPolicy) DeepCopy() *SandboxSuspendPolicy {
	if in == nil {
		return nil
	}
	out := new(SandboxSuspendPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxWorkspaceProfile) DeepCopyInto(out *SandboxWorkspaceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxWorkspaceProfile.
func (in *SandboxWorkspaceProfile) DeepCopy() *SandboxWorkspaceProfile {
	if in == nil {
		return nil
	}
	out := new(SandboxWorkspaceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxWorkspaceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxWorkspaceProfileList) DeepCopyInto(out *SandboxWorkspaceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxWorkspaceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxWorkspaceProfileList.
func (in *SandboxWorkspaceProfileList) DeepCopy() *SandboxWorkspaceProfileList {
	if in == nil {
		return nil
	}
	out := new(SandboxWorkspaceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxWorkspaceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxWorkspaceProfileSpec) DeepCopyInto(out *SandboxWorkspaceProfileSpec) {
	*out = *in
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(SandboxSuspendPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(RetentionPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxWorkspaceProfileSpec.
func (in *SandboxWorkspaceProfileSpec) DeepCopy() *SandboxWorkspaceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxWorkspaceProfileSpec)
	in.DeepCopyInto(out)
	return out
}
