apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd/sandbox.workspace.orka.ai_sandboxworkspaceprofiles.yaml
  - crd/sandbox.workspace.orka.ai_sandboxproviderconfigs.yaml
  - deployment.yaml
  - rbac.yaml
  - registration.yaml
