apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/workspace.orka.ai_executionworkspacecheckpoints.yaml
  - bases/workspace.orka.ai_executionworkspaceclasses.yaml
  - bases/workspace.orka.ai_executionworkspacepools.yaml
  - bases/workspace.orka.ai_executionworkspaceproviders.yaml
  - bases/workspace.orka.ai_executionworkspaces.yaml
