apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd/fake.workspace.orka.ai_fakepoolparameters.yaml
  - crd/fake.workspace.orka.ai_fakeproviderconfigs.yaml
  - deployment.yaml
  - rbac.yaml
  - registration.yaml
